apiVersion: apps/v1
kind: Deployment
metadata:
  name: vacme-ui
  namespace: vacme
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vacme-ui
  template:
    metadata:
      labels:
        app: vacme-ui
    spec:
      containers:
        - name: vacme-ui
          image: golonzovsky/vacme-parser-ui:latest
---
apiVersion: v1
kind: Service
metadata:
  name: vacme-ui
  namespace: vacme
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: vacme-ui
  type: ClusterIP
