controller:
  ingressClass: "nginx"
  replicaCount: "2"
  service:
    loadBalancerIP: ${ip_address_public}
    internal:
      enabled: true
      annotations:
        cloud.google.com/load-balancer-type: "Internal"
      loadBalancerIP: ${ip_address_private}

defaultBackend:
  service:
    omitClusterIP: "true"