apiVersion: apps/v1
kind: Deployment
metadata:
  name: vacme-api
  namespace: vacme
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vacme-api
  template:
    metadata:
      labels:
        app: vacme-api
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
    spec:
      containers:
        - env:
            - name: PLACE_API_KEY
              valueFrom:
                secretKeyRef:
                  key: place_api_key
                  name: vacme-parser
            - name: MAPPING_LOCATION
              value: "locationMapping.json"
            - name: PARSER_API_BASE
              value: "http://vacme-parser:5000"
          image: golonzovsky/vacme-api
          name: debug
          ports:
            - containerPort: 8000
              name: http
          livenessProbe:
            httpGet:
              port: 8000
              path: /health
          readinessProbe:
            httpGet:
              port: 8000
              path: /health
---
apiVersion: v1
kind: Service
metadata:
  name: vacme-api
  namespace: vacme
spec:
  ports:
    - port: 8000
  selector:
    app: vacme-api
